//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileImporter.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class isolado
    {
        public int idisolado { get; set; }
        public int utentNumber { get; set; }
        public int idequipa { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string data { get; set; }
        public sbyte respeito { get; set; }
    }
}
