//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiANEPC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydb_isiEntities : DbContext
    {
        public mydb_isiEntities()
            : base("name=mydb_isiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidades { get; set; }
        public virtual DbSet<encomenda> encomendas { get; set; }
        public virtual DbSet<equipa> equipas { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
    }
}
