//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapDgs.DatabaseEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mybd_soapEntities1 : DbContext
    {
        public mybd_soapEntities1()
            : base("name=mybd_soapEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipa> equipa { get; set; }
        public virtual DbSet<infetado> infetado { get; set; }
        public virtual DbSet<suspeito> suspeito { get; set; }
    }
}
