//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSoap.DatabaseEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mybd_soapEntities : DbContext
    {
        public Mybd_soapEntities()
            : base("name=Mybd_soapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipa> equipas { get; set; }
        public virtual DbSet<infetado> infetadoes { get; set; }
        public virtual DbSet<suspeito> suspeitoes { get; set; }
    }
}
